#!/usr/bin/env bash

echo $'Chose a compiler backend:'
echo $'\t1) Linux AMD64'
echo $'\t2) Windows x86_64'
echo $'\t3) Apple M1'
echo $'\t4) Linux aarch64'
read -p $'Enter option 1-3 (default 1): ' Backend

echo $'Building Linux AMD64\n'

if [ -z ${Backend} ] 
	then Backend="1";
fi

if [ "${Backend}" == "1" ] 
	then Backend="Linux_AMD64";
	else { 
		echo $'Backend option not supported!' 
	       exit 1 
	       }
fi

#gcc nth.c $Backend".c" -onth -g3 -D$Backend
gcc nth.c -onth -g3 -D$Backend